const constants = {
  APISTATUS: "APISTATUS",
  FILEUPLOAD: "FILEUPLOAD",
  TERMSANDCONDITIONS: "TERMSANDCONDITIONS",
  ACCEPT_TERMS_AND_CONDITIONS: "ACCEPT_TERMS_AND_CONDITIONS",
};

export default constants;
