name: Build and Release React App

on:
  push:
    branches: [master]
  workflow_dispatch:
  workflow_call:

env: 
  CI: false
  NODE_OPTIONS: "--max_old_space_size=4096"
  REACT_APP_APIGW_BASE_URL: ${{ secrets.REACT_APP_APIGW_BASE_URL_PROD }}
  AZURE_CREDS: ${{ secrets.SHOONYA_AZURE_CREDS }}
  AZURE_STORAGEKEY: ${{ secrets.DATADAAN_AZURE_STORAGEKEY_PROD }}

jobs:
  cicd:
    name: CICD_PROD
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/webapp
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: Install NPM packages
      run: npm install --f
    
    - name: Build project
      run: npm run build

    - name: Azure login
      uses: azure/login@v1
      with:
          creds: ${{ env.AZURE_CREDS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name datadaanfrontend --account-key ${{ env.AZURE_STORAGEKEY }} -d '$web' -s ./frontend/webapp/build --overwrite

    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --no-wait --content-paths  "/*" --profile-name datadaan --name datadaanfrontend --resource-group shoonya
   
    - name: Azure logout
      run: |
            az logout
      if: always()
