name: Automated Deployment Pipeline
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Building and Deploying containers on VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        password: ${{ secrets.PROD_PASSWORD }}
        script: |
          cd DMU-DataDaan
          git checkout develop
          git pull
          docker-compose up --build -d